# -*- coding: utf-8 -*-
"""
/***************************************************************************
 travelogs_processing
                                 A QGIS plugin
 Анализ травелогов
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-02
        copyright            : (C) 2025 by Alexey Kolesnikov
        email                : alexeykw@mail.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load travelogs_processing class from file travelogs_processing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .travelogs_processing import travelogs_processing
    return travelogs_processing(iface)
